# =========================================================
# LOCAL - SQL SERVER
# =========================================================

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=lunea;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=lunea
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.use_nationalized_character_data=true

server.port=8080

# =========================================================
# SECURITY
# =========================================================

app.jwt.secret=lunea_super_secret_jwt_key_must_be_at_least_32_bytes_long_for_hs256

app.security.cookie-secure=false