spring.application.name=Cosmetic Store Chain Management

spring.datasource.url=jdbc:postgresql://localhost:5433/lunea
spring.datasource.username=lunea
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# App Security & JWT Config
app.jwt.secret=lunea_super_secret_jwt_key_must_be_at_least_32_bytes_long_for_hs256
app.jwt.access-ttl=7200
app.security.cookie-secure=false